apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-hello-deployment
  labels:
    app: k8s-web-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-web-hello
  template:
    metadata:
      labels:
        app: k8s-web-hello
    spec:
      containers:
      - name: k8s-web-hello
        image: sakm/k8s-node-express
        ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: k8s-web-hello-service
spec:
  #deplyoment name
  selector:
    app: k8s-web-hello
  type: LoadBalancer
  ports:
    - protocol : TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001


