apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end-deployment
  template:
    metadata:
      labels:
        app: front-end-deployment
    spec:
      containers:
      - name: front-end-deployment
        image: sakm/hello-world-front-end
        resources:
        ports:
        - containerPort: 3000

--- 

apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  type: LoadBalancer
  selector:
    app: front-end-deployment
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP